"""initial_schema

Revision ID: 10d803cc41aa
Revises: 
Create Date: 2026-07-17 16:01:51.091245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '10d803cc41aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AUDIT_LOG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('entity_name', sa.String(length=500), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AUDIT_LOG_action'), 'AUDIT_LOG', ['action'], unique=False)
    op.create_index(op.f('ix_AUDIT_LOG_entity_type'), 'AUDIT_LOG', ['entity_type'], unique=False)
    op.create_index(op.f('ix_AUDIT_LOG_id'), 'AUDIT_LOG', ['id'], unique=False)
    op.create_index(op.f('ix_AUDIT_LOG_timestamp'), 'AUDIT_LOG', ['timestamp'], unique=False)
    op.create_index(op.f('ix_AUDIT_LOG_username'), 'AUDIT_LOG', ['username'], unique=False)
    op.create_table('CAT_ALCANCE',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CAT_ALCANCE_nombre'), 'CAT_ALCANCE', ['nombre'], unique=True)
    op.create_table('CAT_CANAL_VENTA',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CAT_CANAL_VENTA_nombre'), 'CAT_CANAL_VENTA', ['nombre'], unique=True)
    op.create_table('CAT_DEPARTAMENTOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CAT_DEPARTAMENTOS_nombre'), 'CAT_DEPARTAMENTOS', ['nombre'], unique=True)
    op.create_table('CAT_ESTADOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CAT_ESTADOS_nombre'), 'CAT_ESTADOS', ['nombre'], unique=True)
    op.create_table('CAT_SUBTIPO_NEGOCIO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CAT_SUBTIPO_NEGOCIO_nombre'), 'CAT_SUBTIPO_NEGOCIO', ['nombre'], unique=True)
    op.create_table('CAT_TIPO_NEGOCIO',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CAT_TIPO_NEGOCIO_nombre'), 'CAT_TIPO_NEGOCIO', ['nombre'], unique=True)
    op.create_table('CLASIFICACION_TAMANOS',
    sa.Column('id_clasificacion_tamaño', sa.Integer(), nullable=False),
    sa.Column('clasificacion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_clasificacion_tamaño')
    )
    op.create_index(op.f('ix_CLASIFICACION_TAMANOS_id_clasificacion_tamaño'), 'CLASIFICACION_TAMANOS', ['id_clasificacion_tamaño'], unique=False)
    op.create_table('CLIENTES',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index(op.f('ix_CLIENTES_id_cliente'), 'CLIENTES', ['id_cliente'], unique=False)
    op.create_table('CUADRANTES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CUADRANTES_nombre'), 'CUADRANTES', ['nombre'], unique=True)
    op.create_table('DEPARTAMENTOS',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_departamento')
    )
    op.create_index(op.f('ix_DEPARTAMENTOS_id_departamento'), 'DEPARTAMENTOS', ['id_departamento'], unique=False)
    op.create_table('FOTOS_RAZONES_RECHAZOS',
    sa.Column('id_foto_razon', sa.Integer(), nullable=False),
    sa.Column('id_foto', sa.Integer(), nullable=False),
    sa.Column('id_razones_rechazos', sa.Integer(), nullable=False),
    sa.Column('rechazado_por', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_foto_razon')
    )
    op.create_index(op.f('ix_FOTOS_RAZONES_RECHAZOS_id_foto'), 'FOTOS_RAZONES_RECHAZOS', ['id_foto'], unique=False)
    op.create_index(op.f('ix_FOTOS_RAZONES_RECHAZOS_id_foto_razon'), 'FOTOS_RAZONES_RECHAZOS', ['id_foto_razon'], unique=False)
    op.create_table('JORNADAS_ENCUESTADOR',
    sa.Column('id_jornada', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado_geo', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_jornada')
    )
    op.create_index(op.f('ix_JORNADAS_ENCUESTADOR_id_jornada'), 'JORNADAS_ENCUESTADOR', ['id_jornada'], unique=False)
    op.create_table('MERCADERISTAS',
    sa.Column('id_mercaderista', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_mercaderista')
    )
    op.create_index(op.f('ix_MERCADERISTAS_cedula'), 'MERCADERISTAS', ['cedula'], unique=True)
    op.create_index(op.f('ix_MERCADERISTAS_id_mercaderista'), 'MERCADERISTAS', ['id_mercaderista'], unique=False)
    op.create_table('PRESENTACIONES',
    sa.Column('id_presentacion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('clasificacion_tamanos', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_presentacion')
    )
    op.create_index(op.f('ix_PRESENTACIONES_id_presentacion'), 'PRESENTACIONES', ['id_presentacion'], unique=False)
    op.create_table('PRODUCTORAS',
    sa.Column('id_productora', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_productora')
    )
    op.create_index(op.f('ix_PRODUCTORAS_id_productora'), 'PRODUCTORAS', ['id_productora'], unique=False)
    op.create_table('PUNTOS_INTERES1',
    sa.Column('identificador', sa.String(length=100), nullable=False),
    sa.Column('punto_de_interes', sa.String(length=300), nullable=True),
    sa.Column('Direccion', sa.String(length=500), nullable=True),
    sa.Column('latitud', sa.String(length=50), nullable=True),
    sa.Column('longitud', sa.String(length=50), nullable=True),
    sa.Column('departamento', sa.String(length=200), nullable=True),
    sa.Column('jerarquia_nivel_2', sa.String(length=200), nullable=True),
    sa.Column('jerarquia_nivel_2_2', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=200), nullable=True),
    sa.Column('clasificacion_de_canal', sa.String(length=200), nullable=True),
    sa.Column('radio', sa.String(length=50), nullable=True),
    sa.Column('tiempo_minimo_de_visita', sa.Integer(), nullable=True),
    sa.Column('fecha_creado', sa.DateTime(), nullable=True),
    sa.Column('nivel_de_alcance', sa.String(length=200), nullable=True),
    sa.Column('rif', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('identificador')
    )
    op.create_index(op.f('ix_PUNTOS_INTERES1_identificador'), 'PUNTOS_INTERES1', ['identificador'], unique=False)
    op.create_table('ROLES',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('SERVICIOS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SERVICIOS_nombre'), 'SERVICIOS', ['nombre'], unique=True)
    op.create_table('SUPERVISORES',
    sa.Column('id_supervisor', sa.Integer(), nullable=False),
    sa.Column('nombre_supervisor', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_supervisor')
    )
    op.create_index(op.f('ix_SUPERVISORES_id_supervisor'), 'SUPERVISORES', ['id_supervisor'], unique=False)
    op.create_table('centros_salud',
    sa.Column('id_centro', sa.Integer(), nullable=False),
    sa.Column('nombre_centro', sa.String(length=255), nullable=False),
    sa.Column('direccion_completa', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_centro')
    )
    op.create_index(op.f('ix_centros_salud_id_centro'), 'centros_salud', ['id_centro'], unique=False)
    op.create_table('encuestas_centro',
    sa.Column('id_encuesta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_centro', sa.Integer(), nullable=False),
    sa.Column('fecha_verificacion', sa.Date(), nullable=False),
    sa.Column('fuente_informacion', sa.String(length=255), nullable=False),
    sa.Column('notas_generales', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('id_jornada', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_encuesta')
    )
    op.create_index(op.f('ix_encuestas_centro_id_encuesta'), 'encuestas_centro', ['id_encuesta'], unique=False)
    op.create_table('medico_centro_encuesta',
    sa.Column('id_medico_centro', sa.Integer(), nullable=False),
    sa.Column('id_encuesta', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('piso_consultorio', sa.String(length=50), nullable=True),
    sa.Column('horarios_consulta', sa.String(length=255), nullable=True),
    sa.Column('dias_consulta', sa.String(length=255), nullable=True),
    sa.Column('direccion_especifica', sa.String(), nullable=True),
    sa.Column('clinica2_nombre', sa.String(length=255), nullable=True),
    sa.Column('piso_consultorio2', sa.String(length=50), nullable=True),
    sa.Column('horarios_consulta2', sa.String(length=255), nullable=True),
    sa.Column('dias_consulta2', sa.String(length=255), nullable=True),
    sa.Column('direccion_especifica2', sa.String(), nullable=True),
    sa.Column('valor_consulta_rango', sa.String(length=30), nullable=False),
    sa.Column('promedio_pacientes_semanal_rango', sa.String(length=30), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_medico_centro')
    )
    op.create_index(op.f('ix_medico_centro_encuesta_id_medico_centro'), 'medico_centro_encuesta', ['id_medico_centro'], unique=False)
    op.create_table('medicos',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_medico_externo', sa.String(length=20), nullable=False),
    sa.Column('apellido1', sa.String(length=100), nullable=False),
    sa.Column('apellido2', sa.String(length=100), nullable=True),
    sa.Column('nombre1', sa.String(length=100), nullable=False),
    sa.Column('nombre2', sa.String(length=100), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.Column('sub_especialidad', sa.String(length=100), nullable=True),
    sa.Column('universidad_graduacion', sa.String(length=255), nullable=True),
    sa.Column('nro_MPPS', sa.String(length=50), nullable=True),
    sa.Column('nro_colegiado', sa.String(length=50), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_medico')
    )
    op.create_index(op.f('ix_medicos_id_medico'), 'medicos', ['id_medico'], unique=False)
    op.create_table('ANALISTAS',
    sa.Column('id_analista', sa.Integer(), nullable=False),
    sa.Column('nombre_analista', sa.String(length=200), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['ROLES.id_rol'], ),
    sa.PrimaryKeyConstraint('id_analista')
    )
    op.create_index(op.f('ix_ANALISTAS_id_analista'), 'ANALISTAS', ['id_analista'], unique=False)
    op.create_table('CATEGORIAS',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('nombre_bi', sa.String(length=255), nullable=True),
    sa.Column('id_departamento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_departamento'], ['DEPARTAMENTOS.id_departamento'], ),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_index(op.f('ix_CATEGORIAS_id_categoria'), 'CATEGORIAS', ['id_categoria'], unique=False)
    op.create_table('CAT_CIUDADES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['CAT_DEPARTAMENTOS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departamento_id', 'nombre', name='uq_ciudad_departamento')
    )
    op.create_index(op.f('ix_CAT_CIUDADES_departamento_id'), 'CAT_CIUDADES', ['departamento_id'], unique=False)
    op.create_index(op.f('ix_CAT_CIUDADES_nombre'), 'CAT_CIUDADES', ['nombre'], unique=False)
    op.create_table('MARCAS',
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('id_productora', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_productora'], ['PRODUCTORAS.id_productora'], ),
    sa.PrimaryKeyConstraint('id_marca')
    )
    op.create_index(op.f('ix_MARCAS_id_marca'), 'MARCAS', ['id_marca'], unique=False)
    op.create_table('RUTAS_NUEVAS',
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('ruta', sa.String(length=200), nullable=True),
    sa.Column('servicio', sa.String(length=200), nullable=True),
    sa.Column('coordinador_1', sa.String(length=200), nullable=True),
    sa.Column('coordinador_2', sa.String(length=200), nullable=True),
    sa.Column('supervisor', sa.String(length=200), nullable=True),
    sa.Column('cuadrante', sa.String(length=200), nullable=True),
    sa.Column('id_cliente_exclusivo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente_exclusivo'], ['CLIENTES.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_ruta')
    )
    op.create_index(op.f('ix_RUTAS_NUEVAS_id_ruta'), 'RUTAS_NUEVAS', ['id_ruta'], unique=False)
    op.create_index(op.f('ix_RUTAS_NUEVAS_ruta'), 'RUTAS_NUEVAS', ['ruta'], unique=False)
    op.create_table('SUPERVISORES_CLIENTES',
    sa.Column('id_supervisor', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_supervisor'], ['SUPERVISORES.id_supervisor'], ),
    sa.PrimaryKeyConstraint('id_supervisor', 'id_cliente')
    )
    op.create_table('USUARIOS',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('id_perfil', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['ROLES.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_USUARIOS_id_usuario'), 'USUARIOS', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_USUARIOS_username'), 'USUARIOS', ['username'], unique=True)
    op.create_table('VISITAS_MERCADERISTA',
    sa.Column('id_visita', sa.Integer(), nullable=False),
    sa.Column('id_mercaderista', sa.Integer(), nullable=True),
    sa.Column('identificador_punto_interes', sa.String(length=100), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha_visita', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('tipo_visita', sa.String(length=50), nullable=True),
    sa.Column('estado_data', sa.String(length=50), nullable=True),
    sa.Column('revisada_por', sa.String(length=200), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_mercaderista'], ['MERCADERISTAS.id_mercaderista'], ),
    sa.ForeignKeyConstraint(['identificador_punto_interes'], ['PUNTOS_INTERES1.identificador'], ),
    sa.PrimaryKeyConstraint('id_visita')
    )
    op.create_index(op.f('ix_VISITAS_MERCADERISTA_id_visita'), 'VISITAS_MERCADERISTA', ['id_visita'], unique=False)
    op.create_table('ANALISTAS_CLIENTE',
    sa.Column('id_analista', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_analista'], ['ANALISTAS.id_analista'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_analista', 'id_cliente')
    )
    op.create_table('BALANCES_TOTALES',
    sa.Column('id_balance', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha_balance', sa.DateTime(), nullable=True),
    sa.Column('identificador_pdv', sa.String(length=100), nullable=True),
    sa.Column('mercaderista', sa.String(length=100), nullable=True),
    sa.Column('producto', sa.String(length=255), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('inv_inicial', sa.Float(), nullable=True),
    sa.Column('inv_final', sa.Float(), nullable=True),
    sa.Column('inv_deposito', sa.Float(), nullable=True),
    sa.Column('caras', sa.Integer(), nullable=True),
    sa.Column('precio_bs', sa.Float(), nullable=True),
    sa.Column('precio_ds', sa.Float(), nullable=True),
    sa.Column('id_visita', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_visita'], ['VISITAS_MERCADERISTA.id_visita'], ),
    sa.PrimaryKeyConstraint('id_balance')
    )
    op.create_index(op.f('ix_BALANCES_TOTALES_id_balance'), 'BALANCES_TOTALES', ['id_balance'], unique=False)
    op.create_table('CATEGORIAS_CLIENTES',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['CATEGORIAS.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_categoria', 'id_cliente')
    )
    op.create_table('CHAT_CONVERSACIONES',
    sa.Column('id_conversacion', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('id_punto_interes', sa.String(length=50), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['USUARIOS.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_conversacion')
    )
    op.create_index(op.f('ix_CHAT_CONVERSACIONES_id_cliente'), 'CHAT_CONVERSACIONES', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_CHAT_CONVERSACIONES_id_conversacion'), 'CHAT_CONVERSACIONES', ['id_conversacion'], unique=False)
    op.create_index(op.f('ix_CHAT_CONVERSACIONES_tipo'), 'CHAT_CONVERSACIONES', ['tipo'], unique=False)
    op.create_table('CLIENTES_RUTAS',
    sa.Column('id_cliente_ruta', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_ruta'], ['RUTAS_NUEVAS.id_ruta'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente_ruta')
    )
    op.create_index(op.f('ix_CLIENTES_RUTAS_id_cliente_ruta'), 'CLIENTES_RUTAS', ['id_cliente_ruta'], unique=False)
    op.create_table('FOTOS_TOTALES',
    sa.Column('id_foto', sa.Integer(), nullable=False),
    sa.Column('id_visita', sa.Integer(), nullable=True),
    sa.Column('id_tipo_foto', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('Estado', sa.String(length=50), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('altitud', sa.Float(), nullable=True),
    sa.Column('fecha_disparo', sa.DateTime(), nullable=True),
    sa.Column('fabricante_camara', sa.String(length=200), nullable=True),
    sa.Column('modelo_camara', sa.String(length=200), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('apertura', sa.String(length=50), nullable=True),
    sa.Column('tiempo_exposicion', sa.String(length=50), nullable=True),
    sa.Column('orientacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_visita'], ['VISITAS_MERCADERISTA.id_visita'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_index(op.f('ix_FOTOS_TOTALES_id_foto'), 'FOTOS_TOTALES', ['id_foto'], unique=False)
    op.create_table('MERCADERISTAS_RUTAS',
    sa.Column('id_mercaderista_ruta', sa.Integer(), nullable=False),
    sa.Column('id_mercaderista', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('tipo_ruta', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_mercaderista'], ['MERCADERISTAS.id_mercaderista'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['RUTAS_NUEVAS.id_ruta'], ),
    sa.PrimaryKeyConstraint('id_mercaderista_ruta')
    )
    op.create_index(op.f('ix_MERCADERISTAS_RUTAS_id_mercaderista_ruta'), 'MERCADERISTAS_RUTAS', ['id_mercaderista_ruta'], unique=False)
    op.create_table('PUSH_SUBSCRIPTIONS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mercaderista_cedula', sa.String(length=20), nullable=True),
    sa.Column('endpoint', sa.String(length=1000), nullable=False),
    sa.Column('p256dh', sa.String(length=500), nullable=False),
    sa.Column('auth', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PUSH_SUBSCRIPTIONS_id'), 'PUSH_SUBSCRIPTIONS', ['id'], unique=False)
    op.create_table('RUTAS_ACTIVADAS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('id_mercaderista', sa.Integer(), nullable=True),
    sa.Column('fecha_hora_activacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('tipo_activacion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_mercaderista'], ['MERCADERISTAS.id_mercaderista'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['RUTAS_NUEVAS.id_ruta'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RUTAS_ACTIVADAS_id'), 'RUTAS_ACTIVADAS', ['id'], unique=False)
    op.create_table('RUTA_PROGRAMACION',
    sa.Column('id_programacion', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('id_punto_interes', sa.String(length=100), nullable=True),
    sa.Column('dia', sa.String(length=20), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('prioridad', sa.String(length=50), nullable=True),
    sa.Column('punto_interes', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_punto_interes'], ['PUNTOS_INTERES1.identificador'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['RUTAS_NUEVAS.id_ruta'], ),
    sa.PrimaryKeyConstraint('id_programacion')
    )
    op.create_index(op.f('ix_RUTA_PROGRAMACION_id_programacion'), 'RUTA_PROGRAMACION', ['id_programacion'], unique=False)
    op.create_table('RUTA_PROGRAMACION_CAMBIOS_FUTUROS',
    sa.Column('id_cambio_futuro', sa.Integer(), nullable=False),
    sa.Column('id_programacion', sa.Integer(), nullable=True),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.Column('ruta_nombre', sa.String(length=200), nullable=True),
    sa.Column('id_punto_interes', sa.String(length=100), nullable=True),
    sa.Column('punto_interes_nombre', sa.String(length=300), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=True),
    sa.Column('dia', sa.String(length=20), nullable=True),
    sa.Column('prioridad', sa.String(length=50), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('tipo_cambio', sa.String(length=50), nullable=False),
    sa.Column('fecha_ejecucion', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_ejecutado', sa.DateTime(), nullable=True),
    sa.Column('ejecutado_por', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_ruta'], ['RUTAS_NUEVAS.id_ruta'], ),
    sa.PrimaryKeyConstraint('id_cambio_futuro')
    )
    op.create_index(op.f('ix_RUTA_PROGRAMACION_CAMBIOS_FUTUROS_id_cambio_futuro'), 'RUTA_PROGRAMACION_CAMBIOS_FUTUROS', ['id_cambio_futuro'], unique=False)
    op.create_table('SESIONES_ACTIVAS',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=1000), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('motivo_cierre', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sesion'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_SESIONES_ACTIVAS_id_sesion'), 'SESIONES_ACTIVAS', ['id_sesion'], unique=False)
    op.create_table('SOLICITUDES',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_solicitante', sa.Integer(), nullable=True),
    sa.Column('tipo_solicitud', sa.String(length=100), nullable=False),
    sa.Column('datos', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitante'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_index(op.f('ix_SOLICITUDES_id_solicitud'), 'SOLICITUDES', ['id_solicitud'], unique=False)
    op.create_table('SUBCATEGORIAS',
    sa.Column('id_subcategoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('nombre_bi', sa.String(length=255), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['CATEGORIAS.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_subcategoria')
    )
    op.create_index(op.f('ix_SUBCATEGORIAS_id_subcategoria'), 'SUBCATEGORIAS', ['id_subcategoria'], unique=False)
    op.create_table('SUPERVISORES_RUTAS',
    sa.Column('id_supervisor', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ruta'], ['RUTAS_NUEVAS.id_ruta'], ),
    sa.ForeignKeyConstraint(['id_supervisor'], ['SUPERVISORES.id_supervisor'], ),
    sa.PrimaryKeyConstraint('id_supervisor', 'id_ruta')
    )
    op.create_table('analistas_rutas',
    sa.Column('id_analista', sa.Integer(), nullable=False),
    sa.Column('id_ruta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ruta'], ['RUTAS_NUEVAS.id_ruta'], ),
    sa.PrimaryKeyConstraint('id_analista', 'id_ruta')
    )
    op.create_table('usuario_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_write', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_see_all', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_permisos_id'), 'usuario_permisos', ['id'], unique=False)
    op.create_table('CHAT_MENSAJES_CLIENTE',
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('id_visita', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_conversacion', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('tipo_mensaje', sa.String(length=50), nullable=True),
    sa.Column('visto', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_conversacion'], ['CHAT_CONVERSACIONES.id_conversacion'], ),
    sa.ForeignKeyConstraint(['id_visita'], ['VISITAS_MERCADERISTA.id_visita'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_index(op.f('ix_CHAT_MENSAJES_CLIENTE_id_mensaje'), 'CHAT_MENSAJES_CLIENTE', ['id_mensaje'], unique=False)
    op.create_table('CHAT_PARTICIPANTES',
    sa.Column('id_conversacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_union', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_conversacion'], ['CHAT_CONVERSACIONES.id_conversacion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_conversacion', 'id_usuario')
    )
    op.create_table('NOTIFICACIONES_RECHAZO_FOTOS',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_foto_original', sa.Integer(), nullable=True),
    sa.Column('id_foto_rechazada', sa.Integer(), nullable=True),
    sa.Column('id_visita', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=200), nullable=True),
    sa.Column('punto_venta', sa.String(length=300), nullable=True),
    sa.Column('rechazado_por', sa.String(length=100), nullable=True),
    sa.Column('fecha_rechazo', sa.DateTime(), nullable=True),
    sa.Column('fecha_notificacion', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_foto_original'], ['FOTOS_TOTALES.id_foto'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_index(op.f('ix_NOTIFICACIONES_RECHAZO_FOTOS_id_notificacion'), 'NOTIFICACIONES_RECHAZO_FOTOS', ['id_notificacion'], unique=False)
    op.create_table('PRODUCTS',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('producto_gutrade', sa.String(length=255), nullable=True),
    sa.Column('descripcionbi', sa.String(length=255), nullable=True),
    sa.Column('gramos', sa.Float(), nullable=True),
    sa.Column('cod_bar', sa.String(length=100), nullable=True),
    sa.Column('inagotable', sa.Boolean(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('id_subcategoria', sa.Integer(), nullable=True),
    sa.Column('id_marca', sa.Integer(), nullable=True),
    sa.Column('id_presentacion', sa.Integer(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('id_departamento', sa.Integer(), nullable=True),
    sa.Column('id_productora', sa.Integer(), nullable=True),
    sa.Column('id_clasificacion_tamaño', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_marca'], ['MARCAS.id_marca'], ),
    sa.ForeignKeyConstraint(['id_presentacion'], ['PRESENTACIONES.id_presentacion'], ),
    sa.ForeignKeyConstraint(['id_subcategoria'], ['SUBCATEGORIAS.id_subcategoria'], ),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_index(op.f('ix_PRODUCTS_id_product'), 'PRODUCTS', ['id_product'], unique=False)
    op.create_table('ACTIVACIONES',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador_punto_interes', sa.String(length=100), nullable=True),
    sa.Column('id_mercaderista', sa.Integer(), nullable=True),
    sa.Column('mercaderista_cedula', sa.String(length=20), nullable=True),
    sa.Column('ID_PRODUCT', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('id_foto_antes', sa.Integer(), nullable=True),
    sa.Column('id_foto_despues', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id_ruta', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ID_PRODUCT'], ['PRODUCTS.id_product'], ),
    sa.ForeignKeyConstraint(['id_foto_antes'], ['FOTOS_TOTALES.id_foto'], ),
    sa.ForeignKeyConstraint(['id_foto_despues'], ['FOTOS_TOTALES.id_foto'], ),
    sa.ForeignKeyConstraint(['id_mercaderista'], ['MERCADERISTAS.id_mercaderista'], ),
    sa.ForeignKeyConstraint(['id_ruta'], ['RUTAS_NUEVAS.id_ruta'], ),
    sa.ForeignKeyConstraint(['identificador_punto_interes'], ['PUNTOS_INTERES1.identificador'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ACTIVACIONES_id'), 'ACTIVACIONES', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ACTIVACIONES_id'), table_name='ACTIVACIONES')
    op.drop_table('ACTIVACIONES')
    op.drop_index(op.f('ix_PRODUCTS_id_product'), table_name='PRODUCTS')
    op.drop_table('PRODUCTS')
    op.drop_index(op.f('ix_NOTIFICACIONES_RECHAZO_FOTOS_id_notificacion'), table_name='NOTIFICACIONES_RECHAZO_FOTOS')
    op.drop_table('NOTIFICACIONES_RECHAZO_FOTOS')
    op.drop_table('CHAT_PARTICIPANTES')
    op.drop_index(op.f('ix_CHAT_MENSAJES_CLIENTE_id_mensaje'), table_name='CHAT_MENSAJES_CLIENTE')
    op.drop_table('CHAT_MENSAJES_CLIENTE')
    op.drop_index(op.f('ix_usuario_permisos_id'), table_name='usuario_permisos')
    op.drop_table('usuario_permisos')
    op.drop_table('analistas_rutas')
    op.drop_table('SUPERVISORES_RUTAS')
    op.drop_index(op.f('ix_SUBCATEGORIAS_id_subcategoria'), table_name='SUBCATEGORIAS')
    op.drop_table('SUBCATEGORIAS')
    op.drop_index(op.f('ix_SOLICITUDES_id_solicitud'), table_name='SOLICITUDES')
    op.drop_table('SOLICITUDES')
    op.drop_index(op.f('ix_SESIONES_ACTIVAS_id_sesion'), table_name='SESIONES_ACTIVAS')
    op.drop_table('SESIONES_ACTIVAS')
    op.drop_index(op.f('ix_RUTA_PROGRAMACION_CAMBIOS_FUTUROS_id_cambio_futuro'), table_name='RUTA_PROGRAMACION_CAMBIOS_FUTUROS')
    op.drop_table('RUTA_PROGRAMACION_CAMBIOS_FUTUROS')
    op.drop_index(op.f('ix_RUTA_PROGRAMACION_id_programacion'), table_name='RUTA_PROGRAMACION')
    op.drop_table('RUTA_PROGRAMACION')
    op.drop_index(op.f('ix_RUTAS_ACTIVADAS_id'), table_name='RUTAS_ACTIVADAS')
    op.drop_table('RUTAS_ACTIVADAS')
    op.drop_index(op.f('ix_PUSH_SUBSCRIPTIONS_id'), table_name='PUSH_SUBSCRIPTIONS')
    op.drop_table('PUSH_SUBSCRIPTIONS')
    op.drop_index(op.f('ix_MERCADERISTAS_RUTAS_id_mercaderista_ruta'), table_name='MERCADERISTAS_RUTAS')
    op.drop_table('MERCADERISTAS_RUTAS')
    op.drop_index(op.f('ix_FOTOS_TOTALES_id_foto'), table_name='FOTOS_TOTALES')
    op.drop_table('FOTOS_TOTALES')
    op.drop_index(op.f('ix_CLIENTES_RUTAS_id_cliente_ruta'), table_name='CLIENTES_RUTAS')
    op.drop_table('CLIENTES_RUTAS')
    op.drop_index(op.f('ix_CHAT_CONVERSACIONES_tipo'), table_name='CHAT_CONVERSACIONES')
    op.drop_index(op.f('ix_CHAT_CONVERSACIONES_id_conversacion'), table_name='CHAT_CONVERSACIONES')
    op.drop_index(op.f('ix_CHAT_CONVERSACIONES_id_cliente'), table_name='CHAT_CONVERSACIONES')
    op.drop_table('CHAT_CONVERSACIONES')
    op.drop_table('CATEGORIAS_CLIENTES')
    op.drop_index(op.f('ix_BALANCES_TOTALES_id_balance'), table_name='BALANCES_TOTALES')
    op.drop_table('BALANCES_TOTALES')
    op.drop_table('ANALISTAS_CLIENTE')
    op.drop_index(op.f('ix_VISITAS_MERCADERISTA_id_visita'), table_name='VISITAS_MERCADERISTA')
    op.drop_table('VISITAS_MERCADERISTA')
    op.drop_index(op.f('ix_USUARIOS_username'), table_name='USUARIOS')
    op.drop_index(op.f('ix_USUARIOS_id_usuario'), table_name='USUARIOS')
    op.drop_table('USUARIOS')
    op.drop_table('SUPERVISORES_CLIENTES')
    op.drop_index(op.f('ix_RUTAS_NUEVAS_ruta'), table_name='RUTAS_NUEVAS')
    op.drop_index(op.f('ix_RUTAS_NUEVAS_id_ruta'), table_name='RUTAS_NUEVAS')
    op.drop_table('RUTAS_NUEVAS')
    op.drop_index(op.f('ix_MARCAS_id_marca'), table_name='MARCAS')
    op.drop_table('MARCAS')
    op.drop_index(op.f('ix_CAT_CIUDADES_nombre'), table_name='CAT_CIUDADES')
    op.drop_index(op.f('ix_CAT_CIUDADES_departamento_id'), table_name='CAT_CIUDADES')
    op.drop_table('CAT_CIUDADES')
    op.drop_index(op.f('ix_CATEGORIAS_id_categoria'), table_name='CATEGORIAS')
    op.drop_table('CATEGORIAS')
    op.drop_index(op.f('ix_ANALISTAS_id_analista'), table_name='ANALISTAS')
    op.drop_table('ANALISTAS')
    op.drop_index(op.f('ix_medicos_id_medico'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_medico_centro_encuesta_id_medico_centro'), table_name='medico_centro_encuesta')
    op.drop_table('medico_centro_encuesta')
    op.drop_index(op.f('ix_encuestas_centro_id_encuesta'), table_name='encuestas_centro')
    op.drop_table('encuestas_centro')
    op.drop_index(op.f('ix_centros_salud_id_centro'), table_name='centros_salud')
    op.drop_table('centros_salud')
    op.drop_index(op.f('ix_SUPERVISORES_id_supervisor'), table_name='SUPERVISORES')
    op.drop_table('SUPERVISORES')
    op.drop_index(op.f('ix_SERVICIOS_nombre'), table_name='SERVICIOS')
    op.drop_table('SERVICIOS')
    op.drop_table('ROLES')
    op.drop_index(op.f('ix_PUNTOS_INTERES1_identificador'), table_name='PUNTOS_INTERES1')
    op.drop_table('PUNTOS_INTERES1')
    op.drop_index(op.f('ix_PRODUCTORAS_id_productora'), table_name='PRODUCTORAS')
    op.drop_table('PRODUCTORAS')
    op.drop_index(op.f('ix_PRESENTACIONES_id_presentacion'), table_name='PRESENTACIONES')
    op.drop_table('PRESENTACIONES')
    op.drop_index(op.f('ix_MERCADERISTAS_id_mercaderista'), table_name='MERCADERISTAS')
    op.drop_index(op.f('ix_MERCADERISTAS_cedula'), table_name='MERCADERISTAS')
    op.drop_table('MERCADERISTAS')
    op.drop_index(op.f('ix_JORNADAS_ENCUESTADOR_id_jornada'), table_name='JORNADAS_ENCUESTADOR')
    op.drop_table('JORNADAS_ENCUESTADOR')
    op.drop_index(op.f('ix_FOTOS_RAZONES_RECHAZOS_id_foto_razon'), table_name='FOTOS_RAZONES_RECHAZOS')
    op.drop_index(op.f('ix_FOTOS_RAZONES_RECHAZOS_id_foto'), table_name='FOTOS_RAZONES_RECHAZOS')
    op.drop_table('FOTOS_RAZONES_RECHAZOS')
    op.drop_index(op.f('ix_DEPARTAMENTOS_id_departamento'), table_name='DEPARTAMENTOS')
    op.drop_table('DEPARTAMENTOS')
    op.drop_index(op.f('ix_CUADRANTES_nombre'), table_name='CUADRANTES')
    op.drop_table('CUADRANTES')
    op.drop_index(op.f('ix_CLIENTES_id_cliente'), table_name='CLIENTES')
    op.drop_table('CLIENTES')
    op.drop_index(op.f('ix_CLASIFICACION_TAMANOS_id_clasificacion_tamaño'), table_name='CLASIFICACION_TAMANOS')
    op.drop_table('CLASIFICACION_TAMANOS')
    op.drop_index(op.f('ix_CAT_TIPO_NEGOCIO_nombre'), table_name='CAT_TIPO_NEGOCIO')
    op.drop_table('CAT_TIPO_NEGOCIO')
    op.drop_index(op.f('ix_CAT_SUBTIPO_NEGOCIO_nombre'), table_name='CAT_SUBTIPO_NEGOCIO')
    op.drop_table('CAT_SUBTIPO_NEGOCIO')
    op.drop_index(op.f('ix_CAT_ESTADOS_nombre'), table_name='CAT_ESTADOS')
    op.drop_table('CAT_ESTADOS')
    op.drop_index(op.f('ix_CAT_DEPARTAMENTOS_nombre'), table_name='CAT_DEPARTAMENTOS')
    op.drop_table('CAT_DEPARTAMENTOS')
    op.drop_index(op.f('ix_CAT_CANAL_VENTA_nombre'), table_name='CAT_CANAL_VENTA')
    op.drop_table('CAT_CANAL_VENTA')
    op.drop_index(op.f('ix_CAT_ALCANCE_nombre'), table_name='CAT_ALCANCE')
    op.drop_table('CAT_ALCANCE')
    op.drop_index(op.f('ix_AUDIT_LOG_username'), table_name='AUDIT_LOG')
    op.drop_index(op.f('ix_AUDIT_LOG_timestamp'), table_name='AUDIT_LOG')
    op.drop_index(op.f('ix_AUDIT_LOG_id'), table_name='AUDIT_LOG')
    op.drop_index(op.f('ix_AUDIT_LOG_entity_type'), table_name='AUDIT_LOG')
    op.drop_index(op.f('ix_AUDIT_LOG_action'), table_name='AUDIT_LOG')
    op.drop_table('AUDIT_LOG')
    # ### end Alembic commands ###
