"""create_frequencies_tables

Revision ID: df332ad7f2f5
Revises: 10d803cc41aa
Create Date: 2026-07-20 11:31:32.174417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df332ad7f2f5'
down_revision: Union[str, None] = '10d803cc41aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RAZONES_RECHAZOS',
    sa.Column('id_razones_rechazos', sa.Integer(), nullable=False),
    sa.Column('razon', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id_razones_rechazos')
    )
    op.create_index(op.f('ix_RAZONES_RECHAZOS_id_razones_rechazos'), 'RAZONES_RECHAZOS', ['id_razones_rechazos'], unique=False)
    op.create_table('TIPOS_FOTOS',
    sa.Column('id_tipo_foto', sa.Integer(), nullable=False),
    sa.Column('tipo_foto', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_foto')
    )
    op.create_index(op.f('ix_TIPOS_FOTOS_id_tipo_foto'), 'TIPOS_FOTOS', ['id_tipo_foto'], unique=False)
    op.create_table('dashboard_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('url_html', sa.String(length=1000), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_client_id'), 'dashboard_client', ['id'], unique=False)
    op.create_table('AUDITORIA_CATEGORIAS',
    sa.Column('id_visita', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('aplico_planograma', sa.Integer(), nullable=True),
    sa.Column('lineamiento_marca', sa.Integer(), nullable=True),
    sa.Column('precio_correcto', sa.Integer(), nullable=True),
    sa.Column('limpieza_correcta', sa.Integer(), nullable=True),
    sa.Column('participacion_correcta', sa.Integer(), nullable=True),
    sa.Column('fifo_correcto', sa.Integer(), nullable=True),
    sa.Column('prox_vencer', sa.Integer(), nullable=True),
    sa.Column('prox_vencer_cantidad', sa.Integer(), nullable=True),
    sa.Column('prox_vencer_marca', sa.String(length=200), nullable=True),
    sa.Column('prox_vencer_fecha1', sa.String(length=50), nullable=True),
    sa.Column('prox_vencer_fecha2', sa.String(length=50), nullable=True),
    sa.Column('competencia_actividad', sa.Integer(), nullable=True),
    sa.Column('competencia_material_pop', sa.Integer(), nullable=True),
    sa.Column('competencia_impulsadora', sa.Integer(), nullable=True),
    sa.Column('pop_hablador', sa.Integer(), nullable=True),
    sa.Column('pop_rompetrafico', sa.Integer(), nullable=True),
    sa.Column('pop_otro', sa.String(length=200), nullable=True),
    sa.Column('promo_nuestra', sa.Integer(), nullable=True),
    sa.Column('promo_nuestra_desc', sa.String(length=500), nullable=True),
    sa.Column('promo_competencia', sa.Integer(), nullable=True),
    sa.Column('promo_competencia_desc', sa.String(length=500), nullable=True),
    sa.Column('exhibicion_adicional', sa.Integer(), nullable=True),
    sa.Column('exhibicion_tipos', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['CATEGORIAS.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_visita'], ['VISITAS_MERCADERISTA.id_visita'], ),
    sa.PrimaryKeyConstraint('id_visita', 'id_categoria')
    )
    op.create_table('FRECUENCIAS_PDVS_CLIENTE',
    sa.Column('id_frecuencia_pdv_cliente', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_punto_interes', sa.String(length=100), nullable=False),
    sa.Column('frecuencia_semanal', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_punto_interes'], ['PUNTOS_INTERES1.identificador'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_frecuencia_pdv_cliente')
    )
    op.create_index(op.f('ix_FRECUENCIAS_PDVS_CLIENTE_id_frecuencia_pdv_cliente'), 'FRECUENCIAS_PDVS_CLIENTE', ['id_frecuencia_pdv_cliente'], unique=False)
    op.create_table('HORAS_PROMEDIO_EJECUCION',
    sa.Column('id_horas_promedio_ejecucion', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_tipo_negocio', sa.Integer(), nullable=False),
    sa.Column('minutos_promedio', sa.Integer(), nullable=False),
    sa.Column('fecha_creado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('fecha_modificado', sa.DateTime(), nullable=True),
    sa.Column('id_usuario_creador', sa.Integer(), nullable=True),
    sa.Column('id_usuario_modificador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_tipo_negocio'], ['CAT_TIPO_NEGOCIO.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_creador'], ['USUARIOS.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_modificador'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_horas_promedio_ejecucion')
    )
    op.create_index(op.f('ix_HORAS_PROMEDIO_EJECUCION_id_horas_promedio_ejecucion'), 'HORAS_PROMEDIO_EJECUCION', ['id_horas_promedio_ejecucion'], unique=False)
    op.create_table('VENDEDOR_JORNADAS',
    sa.Column('id_jornada', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_jornada')
    )
    op.create_index(op.f('ix_VENDEDOR_JORNADAS_id_jornada'), 'VENDEDOR_JORNADAS', ['id_jornada'], unique=False)
    op.create_table('VENDEDOR_VISITAS',
    sa.Column('id_visita_vendedor', sa.Integer(), nullable=False),
    sa.Column('id_jornada', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_punto_interes', sa.String(length=100), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('vendio', sa.Boolean(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('razon_no_venta', sa.String(length=500), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['CLIENTES.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_jornada'], ['VENDEDOR_JORNADAS.id_jornada'], ),
    sa.ForeignKeyConstraint(['id_punto_interes'], ['PUNTOS_INTERES1.identificador'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['USUARIOS.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_visita_vendedor')
    )
    op.create_index(op.f('ix_VENDEDOR_VISITAS_id_visita_vendedor'), 'VENDEDOR_VISITAS', ['id_visita_vendedor'], unique=False)
    op.create_foreign_key(None, 'CHAT_MENSAJES_CLIENTE', 'USUARIOS', ['id_usuario'], ['id_usuario'])
    op.add_column('RUTAS_ACTIVADAS', sa.Column('motivo_no_activacion', sa.String(length=500), nullable=True))
    op.add_column('SOLICITUDES', sa.Column('respuesta', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SOLICITUDES', 'respuesta')
    op.drop_column('RUTAS_ACTIVADAS', 'motivo_no_activacion')
    op.drop_constraint(None, 'CHAT_MENSAJES_CLIENTE', type_='foreignkey')
    op.drop_index(op.f('ix_VENDEDOR_VISITAS_id_visita_vendedor'), table_name='VENDEDOR_VISITAS')
    op.drop_table('VENDEDOR_VISITAS')
    op.drop_index(op.f('ix_VENDEDOR_JORNADAS_id_jornada'), table_name='VENDEDOR_JORNADAS')
    op.drop_table('VENDEDOR_JORNADAS')
    op.drop_index(op.f('ix_HORAS_PROMEDIO_EJECUCION_id_horas_promedio_ejecucion'), table_name='HORAS_PROMEDIO_EJECUCION')
    op.drop_table('HORAS_PROMEDIO_EJECUCION')
    op.drop_index(op.f('ix_FRECUENCIAS_PDVS_CLIENTE_id_frecuencia_pdv_cliente'), table_name='FRECUENCIAS_PDVS_CLIENTE')
    op.drop_table('FRECUENCIAS_PDVS_CLIENTE')
    op.drop_table('AUDITORIA_CATEGORIAS')
    op.drop_index(op.f('ix_dashboard_client_id'), table_name='dashboard_client')
    op.drop_table('dashboard_client')
    op.drop_index(op.f('ix_TIPOS_FOTOS_id_tipo_foto'), table_name='TIPOS_FOTOS')
    op.drop_table('TIPOS_FOTOS')
    op.drop_index(op.f('ix_RAZONES_RECHAZOS_id_razones_rechazos'), table_name='RAZONES_RECHAZOS')
    op.drop_table('RAZONES_RECHAZOS')
    # ### end Alembic commands ###
