apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus2di-backend-config
  namespace: qa
data:
  DB_DRIVER: "ODBC Driver 17 for SQL Server"
  DB_SERVER: "172.174.41.110"
  DB_NAME: "epran-qa"
  DB_POOL_SIZE: "5"
  DB_MAX_OVERFLOW: "10"
  ENVIRONMENT: "qa"
  ACCESS_TOKEN_EXPIRE_MINUTES: "480"
  FRONTEND_URL: "https://qa.nexus2di.net"
  AZURE_CONTAINER_NAME: "epran-qa"
  AZURE_ACCOUNT_NAME: "saeprandat001"
  SCHEDULER_INTERVAL_MINUTES: "60"
  SCHEDULER_TIMEZONE: "America/Caracas"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "2"
